name: Main CI

on: pull_request

jobs:
  all-status-check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs:
      - buf-check
      - buf-gen
    steps:
      - name: All status check
        run: echo "All status checks passed"

  buf-check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-action@d5697c6563d51b0247005e9ef64e97277de3a8f5 # V1.0.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  buf-gen:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-action@d5697c6563d51b0247005e9ef64e97277de3a8f5 # V1.0.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          setup_only: true
      - name: buf generate
        run: |
          buf generate
