name: Dispatch lib

on:
  push:
    branches: [main]
    paths:
      - "schema/**"

jobs:
  run_dispatch:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: run dispatch
        run: |
          gh workflow run "Update Schema" -r halcyon-org/blllib
        env:
          GH_TOKEN: ${{ secrets.ORG_TOKEN }}
